import fs from "node:fs";
import path from "node:path";
import { freeformToSvg } from "../lib/diagrams/freeform-svg.ts";
import type { CanvasDocument } from "../lib/diagrams/freeform-canvas.ts";

const ARTIFACT_DIR = "/Users/redforman/.gemini/antigravity/brain/7cb2b6fa-3312-4321-a25d-6ede85631a3c";

export function renderAndSaveCanvasSvg(doc: CanvasDocument, filename: string): string {
  const svg = freeformToSvg(doc);
  const outPath = path.join(ARTIFACT_DIR, filename);
  fs.writeFileSync(outPath, svg, "utf-8");
  return outPath;
}

// Example demo diagram generated by our engine:
const DEMO_ARCHITECTURE: CanvasDocument = {
  version: 1,
  renderMode: "clean",
  shapes: [
    {
      id: "client",
      type: "rectangle",
      x: 60,
      y: 180,
      width: 150,
      height: 80,
      fill: "5",
      stroke: "#2563eb",
      strokeWidth: 2,
      cornerRadius: 8,
      text: { content: "Next.js 16 Client\n(React 19 + Konva)", fontSize: 13, bold: true, align: "center" },
    },
    {
      id: "agent_router",
      type: "rectangle",
      x: 290,
      y: 175,
      width: 170,
      height: 90,
      fill: "1",
      stroke: "#0284c7",
      strokeWidth: 2,
      cornerRadius: 8,
      text: { content: "AI Agent Router\n(Vercel AI SDK v6)", fontSize: 13, bold: true, align: "center" },
    },
    {
      id: "auth_gate",
      type: "diamond",
      x: 530,
      y: 160,
      width: 160,
      height: 120,
      fill: "3",
      stroke: "#d97706",
      strokeWidth: 2,
      text: { content: "Valid Token & Credits?", fontSize: 12, bold: true, align: "center" },
    },
    {
      id: "ops_engine",
      type: "hexagon",
      x: 760,
      y: 80,
      width: 170,
      height: 100,
      fill: "6",
      stroke: "#7c3aed",
      strokeWidth: 2,
      text: { content: "Surgical apply_ops\n(Sub-token Patch)", fontSize: 12, bold: true, align: "center" },
    },
    {
      id: "autolayout",
      type: "star",
      x: 770,
      y: 260,
      width: 150,
      height: 110,
      fill: "4",
      stroke: "#16a34a",
      strokeWidth: 2,
      text: { content: "2ms Auto-Layout\nEngine", fontSize: 12, bold: true, align: "center" },
    },
    {
      id: "postgres",
      type: "cylinder",
      x: 1000,
      y: 65,
      width: 150,
      height: 115,
      fill: "4",
      stroke: "#16a34a",
      strokeWidth: 2,
      text: { content: "Neon Postgres\n(Drizzle ORM)", fontSize: 13, bold: true, align: "center" },
    },
    {
      id: "stripe_cloud",
      type: "cloud",
      x: 1000,
      y: 250,
      width: 160,
      height: 110,
      fill: "2",
      stroke: "#dc2626",
      strokeWidth: 2,
      text: { content: "Stripe Billing\nWebhooks", fontSize: 13, bold: true, align: "center" },
    },
    // Arrows
    {
      id: "a1",
      type: "arrow",
      x: 0,
      y: 0,
      start: { shapeId: "client", anchor: "right" },
      end: { shapeId: "agent_router", anchor: "left" },
      routing: "orthogonal",
      label: "Prompt / Gesture",
    },
    {
      id: "a2",
      type: "arrow",
      x: 0,
      y: 0,
      start: { shapeId: "agent_router", anchor: "right" },
      end: { shapeId: "auth_gate", anchor: "left" },
      label: "HTTP POST",
    },
    {
      id: "a3",
      type: "arrow",
      x: 0,
      y: 0,
      start: { shapeId: "auth_gate", anchor: "top" },
      end: { shapeId: "ops_engine", anchor: "left" },
      routing: "orthogonal",
      label: "Yes",
    },
    {
      id: "a4",
      type: "arrow",
      x: 0,
      y: 0,
      start: { shapeId: "auth_gate", anchor: "bottom" },
      end: { shapeId: "autolayout", anchor: "left" },
      routing: "orthogonal",
      label: "Tidy Up",
    },
    {
      id: "a5",
      type: "arrow",
      x: 0,
      y: 0,
      start: { shapeId: "ops_engine", anchor: "right" },
      end: { shapeId: "postgres", anchor: "left" },
      label: "Save AST",
    },
    {
      id: "a6",
      type: "arrow",
      x: 0,
      y: 0,
      start: { shapeId: "auth_gate", anchor: "right" },
      end: { shapeId: "stripe_cloud", anchor: "left" },
      routing: "orthogonal",
      label: "Checkout Portal",
    },
  ],
};

if (process.argv[1]?.endsWith("render-canvas.ts")) {
  const out = renderAndSaveCanvasSvg(DEMO_ARCHITECTURE, "engine_live_architecture.svg");
  console.log("Rendered engine SVG to:", out);
}
