import fs from "node:fs";
import path from "node:path";
import { freeformToSvg } from "../lib/diagrams/freeform-svg.ts";
import type { CanvasDocument } from "../lib/diagrams/freeform-canvas.ts";

const ARTIFACT_DIR = "/Users/redforman/.gemini/antigravity/brain/7cb2b6fa-3312-4321-a25d-6ede85631a3c";

const PRO_ERP_DOC: CanvasDocument = {
  version: 1,
  renderMode: "clean",
  shapes: [
    // ─── Domain Swimlane Frames ──────────────────────────────────────────────
    { id: "f_crm", type: "frame", name: "1. Customer & Orders Domain (CRM / O2C)", x: 40, y: 40, width: 440, height: 530, fill: "transparent" },
    { id: "f_scm", type: "frame", name: "2. Supply Chain & Fulfillment (SCM)", x: 510, y: 40, width: 440, height: 530, fill: "transparent" },
    { id: "f_fin", type: "frame", name: "3. Enterprise Finance & Banking", x: 980, y: 40, width: 440, height: 530, fill: "transparent" },
    { id: "f_bus", type: "frame", name: "Enterprise Event Mesh & Real-Time Lakehouse", x: 40, y: 600, width: 1380, height: 230, fill: "transparent" },

    // ─── CRM Domain ──────────────────────────────────────────────────────────
    {
      id: "sales_card",
      type: "card",
      parentId: "f_crm",
      x: 70,
      y: 90,
      width: 380,
      height: 125,
      icon: "globe",
      stroke: "#2563eb",
      badge: { text: "STOREFRONT", bg: "#dbeafe", color: "#1d4ed8" },
      title: "Omnichannel B2B Portal",
      subtitle: "Next.js 16 • GraphQL Gateway • Edge CDN",
      metadata: [
        { label: "Rate Limit", value: "10,000 req/sec" },
        { label: "Auth Scope", value: "OAuth2 + RBAC JWT" },
      ],
    },
    {
      id: "credit_gate",
      type: "diamond",
      parentId: "f_crm",
      x: 170,
      y: 245,
      width: 180,
      height: 115,
      fill: "3",
      stroke: "#d97706",
      strokeWidth: 2,
      text: { content: "Credit & Fraud\nChecks Pass?", fontSize: 12, bold: true, align: "center" },
    },
    {
      id: "orders_table",
      type: "table",
      parentId: "f_crm",
      x: 70,
      y: 385,
      width: 380,
      height: 160,
      tableName: "crm_customer_orders",
      stroke: "#0284c7",
      headerBg: "#e0f2fe",
      columns: [
        { name: "id", type: "uuid", isPk: true },
        { name: "customer_id", type: "uuid", isFk: true },
        { name: "total_amount_cents", type: "int8" },
        { name: "order_status", type: "varchar(32)" },
        { name: "created_at", type: "timestamptz" },
      ],
    },

    // ─── SCM Domain ──────────────────────────────────────────────────────────
    {
      id: "mrp_card",
      type: "card",
      parentId: "f_scm",
      x: 540,
      y: 90,
      width: 380,
      height: 125,
      icon: "cpu",
      stroke: "#7c3aed",
      badge: { text: "ENGINE", bg: "#f3e8ff", color: "#6b21a8" },
      title: "Material Requirements (MRP)",
      subtitle: "Automated BOM Allocation & Dispatch",
      metadata: [
        { label: "Cycle Time", value: "< 250ms batch" },
        { label: "Optimization", value: "Heuristic Linear Solver" },
      ],
    },
    {
      id: "wms_card",
      type: "card",
      parentId: "f_scm",
      x: 540,
      y: 240,
      width: 380,
      height: 125,
      icon: "server",
      stroke: "#16a34a",
      badge: { text: "LOGISTICS", bg: "#dcfce7", color: "#15803d" },
      title: "Automated Warehouse (WMS)",
      subtitle: "Robotic Picking & Packing System",
      metadata: [
        { label: "Pick Accuracy", value: "99.98%" },
        { label: "Throughput", value: "1,500 units/hr" },
      ],
    },
    {
      id: "inventory_table",
      type: "table",
      parentId: "f_scm",
      x: 540,
      y: 385,
      width: 380,
      height: 160,
      tableName: "scm_inventory_stock",
      stroke: "#15803d",
      headerBg: "#dcfce7",
      columns: [
        { name: "sku_id", type: "varchar(64)", isPk: true },
        { name: "warehouse_location", type: "varchar(32)" },
        { name: "qty_on_hand", type: "int4" },
        { name: "qty_reserved", type: "int4" },
        { name: "last_counted_at", type: "timestamptz" },
      ],
    },

    // ─── Financials Domain ───────────────────────────────────────────────────
    {
      id: "gl_table",
      type: "table",
      parentId: "f_fin",
      x: 1010,
      y: 90,
      width: 380,
      height: 160,
      tableName: "gl_double_entry_journal",
      stroke: "#0f766e",
      headerBg: "#ccfbf1",
      columns: [
        { name: "entry_id", type: "uuid", isPk: true },
        { name: "account_code", type: "varchar(16)" },
        { name: "debit_cents", type: "int8" },
        { name: "credit_cents", type: "int8" },
        { name: "posted_at", type: "timestamptz" },
      ],
    },
    {
      id: "invoicing_card",
      type: "card",
      parentId: "f_fin",
      x: 1010,
      y: 275,
      width: 380,
      height: 125,
      icon: "credit-card",
      stroke: "#d97706",
      badge: { text: "TAX & AR/AP", bg: "#fef3c7", color: "#b45309" },
      title: "Automated Invoicing Engine",
      subtitle: "Avalara Tax • Peppol e-Invoicing",
      metadata: [
        { label: "Multi-Currency", value: "32 FX Currencies" },
        { label: "Compliance", value: "SOX & GAAP Verified" },
      ],
    },
    {
      id: "bank_card",
      type: "card",
      parentId: "f_fin",
      x: 1010,
      y: 420,
      width: 380,
      height: 125,
      icon: "cloud",
      stroke: "#dc2626",
      badge: { text: "SETTLEMENT", bg: "#fee2e2", color: "#b91c1c" },
      title: "SWIFT & Stripe Clearinghouse",
      subtitle: "Direct Debit • Wire Settlement",
      metadata: [
        { label: "Protocols", value: "ISO 20022 / ACH" },
        { label: "SLA", value: "Instant T+0 Finality" },
      ],
    },

    // ─── Event Mesh & Lakehouse ──────────────────────────────────────────────
    {
      id: "kafka_card",
      type: "card",
      parentId: "f_bus",
      x: 70,
      y: 650,
      width: 580,
      height: 140,
      icon: "queue",
      stroke: "#0284c7",
      badge: { text: "EVENT MESH", bg: "#e0f2fe", color: "#0369a1" },
      title: "Enterprise Kafka Event Streaming Mesh",
      subtitle: "Schema Registry • Debezium CDC Connectors",
      metadata: [
        { label: "Topics", value: "orders.v1, inventory.v2, billing.v1, ledger.v1" },
        { label: "Throughput", value: "1.2M events/sec (sub-5ms p99 latency)" },
      ],
    },
    {
      id: "lakehouse_card",
      type: "card",
      parentId: "f_bus",
      x: 700,
      y: 650,
      width: 400,
      height: 140,
      icon: "database",
      stroke: "#7c3aed",
      badge: { text: "ANALYTICS", bg: "#f3e8ff", color: "#6b21a8" },
      title: "Snowflake & ClickHouse Lakehouse",
      subtitle: "Columnar Storage & Real-Time Aggregations",
      metadata: [
        { label: "Data Freshness", value: "< 2.0s ingestion lag" },
        { label: "Retention", value: "7 Years Immutable Archive" },
      ],
    },
    {
      id: "bi_card",
      type: "card",
      parentId: "f_bus",
      x: 1140,
      y: 650,
      width: 250,
      height: 140,
      icon: "activity",
      stroke: "#16a34a",
      badge: { text: "EXECUTIVE BI", bg: "#dcfce7", color: "#15803d" },
      title: "Real-Time BI Dashboard",
      subtitle: "Live Revenue & Stock KPIs",
      metadata: [
        { label: "Uptime SLA", value: "99.999%" },
        { label: "Refresh", value: "WebSocket Push" },
      ],
    },

    // ─── Inter-domain Smooth Connectors ──────────────────────────────────────
    {
      id: "a1",
      type: "arrow",
      x: 0,
      y: 0,
      start: { shapeId: "sales_card", anchor: "bottom" },
      end: { shapeId: "credit_gate", anchor: "top" },
      routing: "orthogonal",
      label: "Evaluate Customer",
    },
    {
      id: "a2",
      type: "arrow",
      x: 0,
      y: 0,
      start: { shapeId: "credit_gate", anchor: "bottom" },
      end: { shapeId: "orders_table", anchor: "top" },
      routing: "orthogonal",
      label: "Passed (Create Order)",
    },
    {
      id: "a3",
      type: "arrow",
      x: 0,
      y: 0,
      start: { shapeId: "orders_table", anchor: "right" },
      end: { shapeId: "inventory_table", anchor: "left" },
      routing: "orthogonal",
      label: "Reserve Stock",
    },
    {
      id: "a4",
      type: "arrow",
      x: 0,
      y: 0,
      start: { shapeId: "mrp_card", anchor: "bottom" },
      end: { shapeId: "wms_card", anchor: "top" },
      routing: "orthogonal",
      label: "Pick Batch",
    },
    {
      id: "a5",
      type: "arrow",
      x: 0,
      y: 0,
      start: { shapeId: "wms_card", anchor: "bottom" },
      end: { shapeId: "inventory_table", anchor: "top" },
      routing: "orthogonal",
      label: "Deduct Stock",
    },
    {
      id: "a6",
      type: "arrow",
      x: 0,
      y: 0,
      start: { shapeId: "orders_table", anchor: "bottom" },
      end: { shapeId: "kafka_card", anchor: "top" },
      routing: "orthogonal",
      label: "OrderPlaced Event",
    },
    {
      id: "a7",
      type: "arrow",
      x: 0,
      y: 0,
      start: { shapeId: "invoicing_card", anchor: "top" },
      end: { shapeId: "gl_table", anchor: "bottom" },
      routing: "orthogonal",
      label: "Post GL Debit/Credit",
    },
    {
      id: "a8",
      type: "arrow",
      x: 0,
      y: 0,
      start: { shapeId: "invoicing_card", anchor: "bottom" },
      end: { shapeId: "bank_card", anchor: "top" },
      routing: "orthogonal",
      label: "Dispatch Wire / Clearing",
    },
    {
      id: "a9",
      type: "arrow",
      x: 0,
      y: 0,
      start: { shapeId: "kafka_card", anchor: "right" },
      end: { shapeId: "lakehouse_card", anchor: "left" },
      routing: "orthogonal",
      label: "CDC Micro-Batch",
    },
    {
      id: "a10",
      type: "arrow",
      x: 0,
      y: 0,
      start: { shapeId: "lakehouse_card", anchor: "right" },
      end: { shapeId: "bi_card", anchor: "left" },
      routing: "orthogonal",
      label: "Stream Aggregations",
    },
  ],
};

const svg = freeformToSvg(PRO_ERP_DOC);
const outPath = path.join(ARTIFACT_DIR, "enterprise_erp_figma_grade.svg");
fs.writeFileSync(outPath, svg, "utf-8");
console.log("Rendered Figma-grade enterprise ERP SVG to:", outPath);
