import fs from "node:fs";
import path from "node:path";
import { freeformToSvg } from "../lib/diagrams/freeform-svg.ts";
import type { CanvasDocument } from "../lib/diagrams/freeform-canvas.ts";

const ARTIFACT_DIR = "/Users/redforman/.gemini/antigravity/brain/7cb2b6fa-3312-4321-a25d-6ede85631a3c";

const ENTERPRISE_ERP_DOC: CanvasDocument = {
  version: 1,
  renderMode: "clean",
  shapes: [
    // ─── Swimlane Frames ──────────────────────────────────────────────────────
    { id: "f_crm", type: "frame", name: "1. Customer & Sales (CRM)", x: 40, y: 40, width: 340, height: 460, fill: "transparent" },
    { id: "f_scm", type: "frame", name: "2. Supply Chain & Logistics", x: 410, y: 40, width: 340, height: 460, fill: "transparent" },
    { id: "f_fin", type: "frame", name: "3. Financials & General Ledger", x: 780, y: 40, width: 340, height: 460, fill: "transparent" },
    { id: "f_bus", type: "frame", name: "Enterprise Event Mesh & Analytics", x: 40, y: 530, width: 1080, height: 210, fill: "transparent" },

    // ─── CRM Domain ──────────────────────────────────────────────────────────
    {
      id: "sales_portal",
      type: "rectangle",
      parentId: "f_crm",
      x: 70,
      y: 90,
      width: 280,
      height: 75,
      fill: "5",
      stroke: "#2563eb",
      strokeWidth: 2,
      text: { content: "B2B Sales Portal\n(Omnichannel Storefront)", fontSize: 13, bold: true, align: "center" },
    },
    {
      id: "credit_gate",
      type: "diamond",
      parentId: "f_crm",
      x: 120,
      y: 200,
      width: 180,
      height: 120,
      fill: "3",
      stroke: "#d97706",
      strokeWidth: 2,
      text: { content: "Credit Rating & Limits\nApproved?", fontSize: 12, bold: true, align: "center" },
    },
    {
      id: "order_svc",
      type: "rectangle",
      parentId: "f_crm",
      x: 70,
      y: 370,
      width: 280,
      height: 80,
      fill: "1",
      stroke: "#0284c7",
      strokeWidth: 2,
      text: { content: "Order Management System (OMS)\n(Pricing Rules & Contract Terms)", fontSize: 13, bold: true, align: "center" },
    },

    // ─── SCM Domain ──────────────────────────────────────────────────────────
    {
      id: "mrp_engine",
      type: "rectangle",
      parentId: "f_scm",
      x: 440,
      y: 90,
      width: 280,
      height: 75,
      fill: "6",
      stroke: "#7c3aed",
      strokeWidth: 2,
      text: { content: "Material Requirements (MRP)\n(BOM & Production Scheduling)", fontSize: 13, bold: true, align: "center" },
    },
    {
      id: "wms_system",
      type: "hexagon",
      parentId: "f_scm",
      x: 460,
      y: 215,
      width: 240,
      height: 95,
      fill: "4",
      stroke: "#16a34a",
      strokeWidth: 2,
      text: { content: "Warehouse & Picking (WMS)\n(Automated Fulfillment)", fontSize: 12, bold: true, align: "center" },
    },
    {
      id: "inventory_db",
      type: "cylinder",
      parentId: "f_scm",
      x: 480,
      y: 350,
      width: 200,
      height: 110,
      fill: "4",
      stroke: "#15803d",
      strokeWidth: 2,
      text: { content: "Global Inventory DB\n(Multi-location Stock)", fontSize: 13, bold: true, align: "center" },
    },

    // ─── Financials Domain ───────────────────────────────────────────────────
    {
      id: "gl_ledger",
      type: "cylinder",
      parentId: "f_fin",
      x: 850,
      y: 80,
      width: 200,
      height: 110,
      fill: "4",
      stroke: "#15803d",
      strokeWidth: 2,
      text: { content: "General Ledger DB (GL)\n(Double-Entry Immutability)", fontSize: 13, bold: true, align: "center" },
    },
    {
      id: "ap_ar_engine",
      type: "rectangle",
      parentId: "f_fin",
      x: 810,
      y: 220,
      width: 280,
      height: 80,
      fill: "3",
      stroke: "#d97706",
      strokeWidth: 2,
      text: { content: "AP / AR & Invoicing Engine\n(Automated Tax & Reconciliation)", fontSize: 13, bold: true, align: "center" },
    },
    {
      id: "bank_gateway",
      type: "cloud",
      parentId: "f_fin",
      x: 830,
      y: 350,
      width: 240,
      height: 110,
      fill: "2",
      stroke: "#dc2626",
      strokeWidth: 2,
      text: { content: "SWIFT / Banking & Stripe\n(Settlement & Clearing)", fontSize: 13, bold: true, align: "center" },
    },

    // ─── Bus & Analytics Domain ──────────────────────────────────────────────
    {
      id: "kafka_mesh",
      type: "rectangle",
      parentId: "f_bus",
      x: 70,
      y: 570,
      width: 650,
      height: 65,
      fill: "1",
      stroke: "#0284c7",
      strokeWidth: 2,
      text: { content: "Enterprise Event Bus (Apache Kafka / Event Mesh)", fontSize: 14, bold: true, align: "center" },
    },
    {
      id: "lakehouse",
      type: "cylinder",
      parentId: "f_bus",
      x: 770,
      y: 550,
      width: 160,
      height: 105,
      fill: "6",
      stroke: "#7c3aed",
      strokeWidth: 2,
      text: { content: "OLAP Lakehouse\n(Snowflake / ClickHouse)", fontSize: 12, bold: true, align: "center" },
    },
    {
      id: "bi_dash",
      type: "star",
      parentId: "f_bus",
      x: 960,
      y: 550,
      width: 140,
      height: 115,
      fill: "3",
      stroke: "#d97706",
      strokeWidth: 2,
      text: { content: "Executive\nBI KPIs", fontSize: 12, bold: true, align: "center" },
    },

    // ─── Inter-domain Connectors ─────────────────────────────────────────────
    {
      id: "a1",
      type: "arrow",
      x: 0,
      y: 0,
      start: { shapeId: "sales_portal", anchor: "bottom" },
      end: { shapeId: "credit_gate", anchor: "top" },
      label: "Validate Terms",
    },
    {
      id: "a2",
      type: "arrow",
      x: 0,
      y: 0,
      start: { shapeId: "credit_gate", anchor: "bottom" },
      end: { shapeId: "order_svc", anchor: "top" },
      label: "Pass (Terms Approved)",
    },
    {
      id: "a3",
      type: "arrow",
      x: 0,
      y: 0,
      start: { shapeId: "order_svc", anchor: "right" },
      end: { shapeId: "inventory_db", anchor: "left" },
      routing: "orthogonal",
      label: "Reserve Inventory",
    },
    {
      id: "a4",
      type: "arrow",
      x: 0,
      y: 0,
      start: { shapeId: "mrp_engine", anchor: "bottom" },
      end: { shapeId: "wms_system", anchor: "top" },
      label: "Dispatch Pick Wave",
    },
    {
      id: "a5",
      type: "arrow",
      x: 0,
      y: 0,
      start: { shapeId: "wms_system", anchor: "bottom" },
      end: { shapeId: "inventory_db", anchor: "top" },
      label: "Deduct Stock",
    },
    {
      id: "a6",
      type: "arrow",
      x: 0,
      y: 0,
      start: { shapeId: "order_svc", anchor: "bottom" },
      end: { shapeId: "kafka_mesh", anchor: "top" },
      label: "OrderCreated Event",
    },
    {
      id: "a7",
      type: "arrow",
      x: 0,
      y: 0,
      start: { shapeId: "ap_ar_engine", anchor: "top" },
      end: { shapeId: "gl_ledger", anchor: "bottom" },
      label: "Post Journal Entry",
    },
    {
      id: "a8",
      type: "arrow",
      x: 0,
      y: 0,
      start: { shapeId: "ap_ar_engine", anchor: "bottom" },
      end: { shapeId: "bank_gateway", anchor: "top" },
      label: "Direct Debit / Wire",
    },
    {
      id: "a9",
      type: "arrow",
      x: 0,
      y: 0,
      start: { shapeId: "kafka_mesh", anchor: "right" },
      end: { shapeId: "lakehouse", anchor: "left" },
      label: "CDC Stream",
    },
    {
      id: "a10",
      type: "arrow",
      x: 0,
      y: 0,
      start: { shapeId: "lakehouse", anchor: "right" },
      end: { shapeId: "bi_dash", anchor: "left" },
      label: "Real-time Metrics",
    },
  ],
};

const svg = freeformToSvg(ENTERPRISE_ERP_DOC);
const outPath = path.join(ARTIFACT_DIR, "enterprise_erp_architecture.svg");
fs.writeFileSync(outPath, svg, "utf-8");
console.log("Rendered enterprise ERP diagram to:", outPath);
